# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  job_super-linter:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job_ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: prep env.
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew clean ktlint

  job_datekt:
    name: datekt
    needs: job_ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: prep env.
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew clean datekt

  job_lintManifestTestDebug:
    name: lintManifestTestDebug
    needs: job_super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: prep env.
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew clean lintManifestTestDebug

  job_lintGooglePlayDebug:
    name: lintGooglePlayDebug
    needs: job_super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: prep env.
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew clean lintGooglePlayDebug

  job_lintFdroidDebug:
    name: lintFdroidDebug
    needs: job_super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: prep env.
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: gradlew
        run: |
          set -x
          ./gradlew clean lintFdroidDebug

  job_connectedGoogleplayDebugAndroidTest:
    name: connectedGoogleplayDebugAndroidTest
    needs: [job_lintManifestTestDebug, job_lintGooglePlayDebug, job_lintFdroidDebug, job_datekt]
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [24, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: prep env.
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: androidTest
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{matrix.api-level}}
          target: default
          script: ./gradlew connectedGoogleplayDebugAndroidTest --stacktrace
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job_connectedFdroidDebugAndroidTest:
    name: connectedFdroidDebugAndroidTest
    needs: job_connectedGoogleplayDebugAndroidTest
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [24, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: prep env.
        run: |
          set -x
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: androidTest
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{matrix.api-level}}
          target: default
          script: ./gradlew connectedGoogleplayDebugAndroidTest --stacktrace
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}