name: fdroid

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [24, 29]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: static analysis
        run: |
          set -x
          ./gradlew lintFdroidDebug ktlint datekt

          - name: test + androidTest
            uses: reactivecircus/android-emulator-runner@v2
            with:
              api-level: ${{ matrix.api-level }}
              target: default
              script: ./gradlew testFdroidDebugUnitTest connectedFdroidDebugAndroidTest --stacktrace
